# Discontinuous Galerkin Differential Equation Solver

Taken within the context of seismic imaging, the program takes the mesh files generated by Triangle and TetGen software, does its magic, then returns the solution to the Acoustic Wave Equation (hoping to extend this to other Differential Equations).






